joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

force1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: force1
  pid:
    p: 100.0
    i: 0.01
    d: 10.0
test2:
    gazebo_ros_control:
        robot_namespace: /test2
        pid_gains:
            force1: {p: 100.0, i: 0.01, d: 10.0}

# test2:
#     joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 50

#     force1_velocity_controller:
#     type: effort_controllers/JointVelocityController
#     joint: force1
#     pid: {p: 100.0, i: 0.01, d: 10.0}